# Generated by Django 5.1.1 on 2024-09-22 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_company_options'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='company',
            field=models.ForeignKey(default='VAP', on_delete=django.db.models.deletion.CASCADE, to='Account.company'),
            preserve_default=False,
        ),
    ]
